[dependencies]
reqwest = "0.12.3"
reqwest-oauth1 = "0.2.4"
serde = "1.0.198"
serde_json = "1.0.116"
tokio = "1.37.0"
cli = "0.0.1"
clap = "4.5.4"
anyhow = "1.0.82"
casual_logger = "0.6.5"
discord = "0.8.1"
#serde = { version = "1.0", features = ["derive"] }  
#tokio = { version = "1", features = ["full"] }